In [7]:
from sklearn.metrics import classification_report
import numpy as np

In [8]:
y_true = [0, 1, 0, 1, 1]
y_pred = [0, 0, 1, 1, 0]
#target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_true, y_pred, labels=[0,1]))#, target_names=target_names))
              



              precision    recall  f1-score   support

           0       0.33      0.50      0.40         2
           1       0.50      0.33      0.40         3

    accuracy                           0.40         5
   macro avg       0.42      0.42      0.40         5
weighted avg       0.43      0.40      0.40         5



In [15]:
y_true = np.array([[1, 0, 1],
                  [0, 1, 0],
                  [0, 1, 0]])
y_pred = np.array([[1, 0, 0],
                  [0, 1, 1],
                  [0, 1, 0]])
print(classification_report(y_true, y_pred,labels=[0,1]))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

   micro avg       1.00      1.00      1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3
 samples avg       1.00      1.00      1.00         3



In [16]:
from sklearn.metrics import f1_score

In [20]:
f1_score(y_true, y_pred, average='weighted')

0.75

In [14]:
y_true

array([[1, 0, 1],
       [0, 1, 0]])

In [7]:
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix

In [8]:
y_true = np.array([[1, 0, 1],
                   [0, 1, 0]])
y_pred = np.array([[1, 0, 0],
                   [0, 1, 1]])
multilabel_confusion_matrix(y_true, y_pred)

array([[[1, 0],
        [0, 1]],

       [[1, 0],
        [0, 1]],

       [[0, 1],
        [1, 0]]])

In [9]:
y_true = [0, 0, 1, 0, 1, 0]
y_pred = [0, 1, 0, 1, 1, 0]
multilabel_confusion_matrix(y_true, y_pred, labels=[0,1])

array([[[1, 1],
        [2, 2]],

       [[2, 2],
        [1, 1]]])